repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: flake8
      exclude: migrations/
      additional_dependencies: [
        "pydocstyle<4.0",
        "flake8-bandit",
        "flake8-bugbear",
        "flake8-docstrings",
        "flake8-import-order ",
        "flake8-string-format",
        "flake8-tidy-imports"
      ]