[tool.poetry]
name = "site"
version = "1.0.0"
description = "The project responsible for maintaining our website and all of its subdomains."
authors = ["Python Discord <info@pythondiscord.com>"]
license = "MIT"

[tool.poetry.dependencies]
django = "~=3.1.14"
django-distill = "~=2.9.0"
django-environ = "~=0.4.5"
django-filter = "~=21.1"
django-prometheus = "~=2.1"
django-simple-bulma = "~=2.4"
djangorestframework = "~=3.12.0"
gunicorn = "~=20.0.4"
markdown = "~=3.3.4"
psycopg2-binary = "~=2.8.0"
python = "3.9.*"
python-frontmatter = "~=1.0"
pyyaml = "~=5.1"
requests = "~=2.21"
sentry-sdk = "~=0.19"
whitenoise = "~=5.0"

[tool.poetry.dev-dependencies]
coverage = "~=5.0"
coveralls = "~=2.1"
flake8 = "~=3.7"
flake8-annotations = "~=2.0"
flake8-bandit = "~=2.1"
flake8-bugbear = "~=20.1"
flake8-docstrings = "~=1.5"
flake8-import-order = "~=0.18"
flake8-string-format = "~=0.3"
flake8-tidy-imports = "~=4.0"
flake8-todo = "~=0.7"
mccabe = "~=0.6.1"
pep8-naming = "~=0.9"
pre-commit = "~=2.1"
pyfakefs = "~=4.5"
python-dotenv = "~=0.17.1"
taskipy = "~=1.7.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.taskipy.tasks]
django_shell = "python manage.py shell"
lint = "pre-commit run --all-files"
makemigrations = "python manage.py makemigrations"
precommit = "pre-commit install"
report = "coverage report -m"
start = "python manage.py run --debug"
test = "coverage run manage.py test"
