[tool.poetry]
name = "pysite"
version = "0.1.0"
description = "Django website for the Python Discord server."
authors = ["Python Discord"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
django = "^2.1"
django-crispy-forms = "^1.7"
django-environ = "^0.4.5"
django-filter = "^2.1"
django-hosts = "^3.0"
djangorestframework = "^3.9"
djangorestframework-bulk = "^0.2.1"
psycopg2-binary = "^2.7"
# `deploy` extra
uwsgi = { version = "^2.0.17.1", optional = true }

[tool.poetry.dev-dependencies]
# `lint` extra
flake8 = { version = "^3.7", optional = true }
flake8-bandit = { version = "^2.1", optional = true }
flake8-bugbear = { version = "^18.8", optional = true }
flake8-import-order = { version = "^0.18.0", optional = true }
flake8-string-format = { version = "^0.2.3", optional = true }
flake8-tidy-imports = { version = "^2.0", optional = true }
mccabe = { version = "^0.6.1", optional = true }
pep8-naming = { version = "^0.8.0", optional = true }
# `test` extra
coverage = { version = "^4.5", optional = true }
# `ci` extra
unittest-xml-reporting = { version = "^2.2.1", optional = true }

[tool.poetry.extras]
deploy = ["uwsgi"]
lint = ["flake8", "flake8-bandit", "flake8-bugbear", "flake8-import-order", "flake8-string-format", "flake8-tidy-imports", "mccabe", "pep8-naming"]
test = ["coverage"]
ci = ["unittest-xml-reporting"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
