[tool.poetry]
name = "site"
version = "1.0.0"
description = "The project responsible for maintaining our website and all of its subdomains."
authors = ["Python Discord <info@pythondiscord.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.9.*"
django = "4.0"  # 4.1 blocked by upstream bug, wait for 4.1.1: https://code.djangoproject.com/ticket/33919
django-environ = "0.9.0"
django-filter = "22.1"
djangorestframework = "3.13.1"
psycopg2-binary = "2.9.3"
django-simple-bulma = "2.5.0"
whitenoise = "6.2.0"
httpx = "0.23.0"
pyyaml = "6.0"
gunicorn = "20.1.0"
sentry-sdk = "1.9.5"
markdown = "3.4.1"
python-frontmatter = "1.0.0"
django-prometheus = "2.2.0"
django-distill = "3.0.1"
PyJWT = {version = "2.4.0", extras = ["crypto"]}

[tool.poetry.dev-dependencies]
coverage = "6.4.4"
flake8 = "~=3.7"
flake8-annotations = "~=2.0"
flake8-bandit = "~=3.0"
flake8-bugbear = "~=20.1"
flake8-docstrings = "~=1.5"
flake8-import-order = "~=0.18"
flake8-string-format = "~=0.3"
flake8-tidy-imports = "~=4.0"
flake8-todo = "~=0.7"
mccabe = "~=0.6.1"
pep8-naming = "~=0.9"
pre-commit = "~=2.1"
pyfakefs = "~=4.5"
coveralls = "3.3.1"
taskipy = "~=1.7.0"
python-dotenv = "~=0.17.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.taskipy.tasks]
start = "python manage.py run --debug"
makemigrations = "python manage.py makemigrations"
django_shell = "python manage.py shell"
test = "coverage run manage.py test"
coverage = "coverage run manage.py test --no-input && coverage report -m"
report = "coverage report -m"
lint = "pre-commit run --all-files"
precommit = "pre-commit install"
static = "python manage.py distill-local build --traceback --force"
